// Generated by Framer (6aa4fc0)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Ticker from "https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/LHz3bw67SqHRmnCKTlE6/Ticker.js";
import ReviewCard from "https://framerusercontent.com/modules/k6JJwIpfKgqp0NlN8HMy/7LzvPcg02zjTnJVOgvWR/N49YAfiyO.js";
import Slideshow from "https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/gveXKR6bwXNSCLv12kr3/SlideShow.js";
const ReviewCardFonts = getFonts(ReviewCard);
const TickerFonts = getFonts(Ticker);
const SlideshowFonts = getFonts(Slideshow);
const cycleOrder = ["weqKRlLlh", "D70eLlKIA"];
const serializationHash = "framer-Gb85t";
const variantClassNames = {
    D70eLlKIA: "framer-v-gh6fsa",
    weqKRlLlh: "framer-v-prv7f3"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const addImageAlt = (image, alt) => {
    if (!image || typeof image !== "object") {
        return;
    }
    return { ...image,
        alt
    };
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "weqKRlLlh",
    Mobile: "D70eLlKIA"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "weqKRlLlh"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "weqKRlLlh",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "D70eLlKIA") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "D70eLlKIA") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-prv7f3", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "weqKRlLlh",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        D70eLlKIA: {
                            "data-framer-name": "Mobile"
                        }
                    }, baseVariant, gestureVariant),
                    children: [isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1r47pz1-container",
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "fPmk9cyBi-container",
                            nodeId: "fPmk9cyBi",
                            rendersWithMotion: true,
                            scopeId: "u37Ksg0Ot",
                            children: /*#__PURE__*/ _jsx(Ticker, {
                                alignment: "center",
                                direction: "left",
                                fadeOptions: {
                                    fadeAlpha: 0,
                                    fadeContent: false,
                                    fadeInset: 0,
                                    fadeWidth: 25,
                                    overflow: true
                                },
                                gap: 32,
                                height: "100%",
                                hoverFactor: .5,
                                id: "fPmk9cyBi",
                                layoutId: "fPmk9cyBi",
                                padding: 0,
                                paddingBottom: 0,
                                paddingLeft: 0,
                                paddingPerSide: false,
                                paddingRight: 0,
                                paddingTop: 0,
                                sizingOptions: {
                                    heightType: false,
                                    widthType: true
                                },
                                slots: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1gl0j1n-container",
                                        "data-framer-name": "Review 1",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "PfVGrK8Eu-container",
                                        name: "Review 1",
                                        nodeId: "PfVGrK8Eu",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "PfVGrK8Eu",
                                            layoutId: "PfVGrK8Eu",
                                            name: "Review 1",
                                            NQ6B20sX9: "Darma Gunawan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Fasiltas lengkap dan super bersih. Kasur spring bednya empuk banget, tidur jadi makin nyenyak dan bangun fresh tiap pagi.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1280,
                                                pixelWidth: 960,
                                                src: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp",
                                                srcSet: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp?scale-down-to=1024 768w,https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp 960w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1nvjbrn-container",
                                        "data-framer-name": "Review 2",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "a46o4u2Vr-container",
                                        name: "Review 2",
                                        nodeId: "a46o4u2Vr",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "a46o4u2Vr",
                                            layoutId: "a46o4u2Vr",
                                            name: "Review 2",
                                            NQ6B20sX9: "Rayhan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Lokasinya tuh mantap banget, gampang banget akses ke mana-mana. Deket mall, transportasi, sama tempat nongkrong hits. Pokoknya praktis!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp",
                                                srcSet: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-igbayv-container",
                                        "data-framer-name": "Review 3",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "pkAzOLoRU-container",
                                        name: "Review 3",
                                        nodeId: "pkAzOLoRU",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "pkAzOLoRU",
                                            layoutId: "pkAzOLoRU",
                                            name: "Review 3",
                                            NQ6B20sX9: "Adam",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Promo buat penghuni baru bikin kantong nggak bolong! Diskonnya asik, plus laundry gratis bikin hidup jadi makin mudah.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 640,
                                                pixelWidth: 640,
                                                src: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp",
                                                srcSet: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp?scale-down-to=512 512w,https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp 640w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1rjk45j-container",
                                        "data-framer-name": "Review 4",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "H5brTFDHx-container",
                                        name: "Review 4",
                                        nodeId: "H5brTFDHx",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "H5brTFDHx",
                                            layoutId: "H5brTFDHx",
                                            name: "Review 4",
                                            NQ6B20sX9: "Salsa",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Kebersihan dan keamanan selalu top! Kosrutdua serius banget jaga kenyamanan penghuninya, jadi aku selalu tenang tinggal di sini.",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp",
                                                srcSet: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1ckxv38-container",
                                        "data-framer-name": "Review 5",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "V8rZpDF2c-container",
                                        name: "Review 5",
                                        nodeId: "V8rZpDF2c",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "V8rZpDF2c",
                                            layoutId: "V8rZpDF2c",
                                            name: "Review 5",
                                            NQ6B20sX9: "Ibnu",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Suasananya cozy dan tenang, cocok banget buat yang suka fokus belajar atau kerja. Fasilitas masaknya lengkap, tinggal masak deh kapan aja!",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 603,
                                                pixelWidth: 632,
                                                src: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp",
                                                srcSet: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp?scale-down-to=512 512w,https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp 632w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-11gkorv-container",
                                        "data-framer-name": "Review 6",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "mHbGMiop_-container",
                                        name: "Review 6",
                                        nodeId: "mHbGMiop_",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "mHbGMiop_",
                                            layoutId: "mHbGMiop_",
                                            name: "Review 6",
                                            NQ6B20sX9: "Noel",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "WiFi super kenceng dan stabil abis, nggak ada drama buffering pas kerja online atau streaming. Bikin semangat kerja di kos!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 610,
                                                pixelWidth: 580,
                                                src: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp",
                                                srcSet: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp 580w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                })],
                                speed: 35,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    }), isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-9ex90p-container",
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "MMli2_Dfq-container",
                            nodeId: "MMli2_Dfq",
                            rendersWithMotion: true,
                            scopeId: "u37Ksg0Ot",
                            children: /*#__PURE__*/ _jsx(Ticker, {
                                alignment: "center",
                                direction: "right",
                                fadeOptions: {
                                    fadeAlpha: 0,
                                    fadeContent: false,
                                    fadeInset: 0,
                                    fadeWidth: 25,
                                    overflow: true
                                },
                                gap: 32,
                                height: "100%",
                                hoverFactor: .5,
                                id: "MMli2_Dfq",
                                layoutId: "MMli2_Dfq",
                                padding: 0,
                                paddingBottom: 0,
                                paddingLeft: 0,
                                paddingPerSide: false,
                                paddingRight: 0,
                                paddingTop: 0,
                                sizingOptions: {
                                    heightType: false,
                                    widthType: true
                                },
                                slots: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-11gkorv-container",
                                        "data-framer-name": "Review 6",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "mHbGMiop_-container",
                                        name: "Review 6",
                                        nodeId: "mHbGMiop_",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "mHbGMiop_",
                                            layoutId: "mHbGMiop_",
                                            name: "Review 6",
                                            NQ6B20sX9: "Noel",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "WiFi super kenceng dan stabil abis, nggak ada drama buffering pas kerja online atau streaming. Bikin semangat kerja di kos!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 610,
                                                pixelWidth: 580,
                                                src: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp",
                                                srcSet: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp 580w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1ckxv38-container",
                                        "data-framer-name": "Review 5",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "V8rZpDF2c-container",
                                        name: "Review 5",
                                        nodeId: "V8rZpDF2c",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "V8rZpDF2c",
                                            layoutId: "V8rZpDF2c",
                                            name: "Review 5",
                                            NQ6B20sX9: "Ibnu",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Suasananya cozy dan tenang, cocok banget buat yang suka fokus belajar atau kerja. Fasilitas masaknya lengkap, tinggal masak deh kapan aja!",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 603,
                                                pixelWidth: 632,
                                                src: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp",
                                                srcSet: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp?scale-down-to=512 512w,https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp 632w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1rjk45j-container",
                                        "data-framer-name": "Review 4",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "H5brTFDHx-container",
                                        name: "Review 4",
                                        nodeId: "H5brTFDHx",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "H5brTFDHx",
                                            layoutId: "H5brTFDHx",
                                            name: "Review 4",
                                            NQ6B20sX9: "Salsa",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Kebersihan dan keamanan selalu top! Kosrutdua serius banget jaga kenyamanan penghuninya, jadi aku selalu tenang tinggal di sini.",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp",
                                                srcSet: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-igbayv-container",
                                        "data-framer-name": "Review 3",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "pkAzOLoRU-container",
                                        name: "Review 3",
                                        nodeId: "pkAzOLoRU",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "pkAzOLoRU",
                                            layoutId: "pkAzOLoRU",
                                            name: "Review 3",
                                            NQ6B20sX9: "Adam",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Promo buat penghuni baru bikin kantong nggak bolong! Diskonnya asik, plus laundry gratis bikin hidup jadi makin mudah.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 640,
                                                pixelWidth: 640,
                                                src: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp",
                                                srcSet: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp?scale-down-to=512 512w,https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp 640w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1nvjbrn-container",
                                        "data-framer-name": "Review 2",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "a46o4u2Vr-container",
                                        name: "Review 2",
                                        nodeId: "a46o4u2Vr",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "a46o4u2Vr",
                                            layoutId: "a46o4u2Vr",
                                            name: "Review 2",
                                            NQ6B20sX9: "Rayhan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Lokasinya tuh mantap banget, gampang banget akses ke mana-mana. Deket mall, transportasi, sama tempat nongkrong hits. Pokoknya praktis!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp",
                                                srcSet: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1gl0j1n-container",
                                        "data-framer-name": "Review 1",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "PfVGrK8Eu-container",
                                        name: "Review 1",
                                        nodeId: "PfVGrK8Eu",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "PfVGrK8Eu",
                                            layoutId: "PfVGrK8Eu",
                                            name: "Review 1",
                                            NQ6B20sX9: "Darma Gunawan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Fasiltas lengkap dan super bersih. Kasur spring bednya empuk banget, tidur jadi makin nyenyak dan bangun fresh tiap pagi.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1280,
                                                pixelWidth: 960,
                                                src: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp",
                                                srcSet: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp?scale-down-to=1024 768w,https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp 960w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                })],
                                speed: 35,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1nhil04-container",
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "P9kZnKNgR-container",
                            nodeId: "P9kZnKNgR",
                            rendersWithMotion: true,
                            scopeId: "u37Ksg0Ot",
                            children: /*#__PURE__*/ _jsx(Slideshow, {
                                alignment: "flex-start",
                                arrowOptions: {
                                    arrowFill: "rgba(0, 0, 0, 0.2)",
                                    arrowGap: 10,
                                    arrowPadding: -10,
                                    arrowPaddingBottom: 0,
                                    arrowPaddingLeft: 0,
                                    arrowPaddingRight: 0,
                                    arrowPaddingTop: 0,
                                    arrowPosition: "auto",
                                    arrowRadius: 40,
                                    arrowShouldFadeIn: false,
                                    arrowShouldSpace: true,
                                    arrowSize: 40,
                                    showMouseControls: false
                                },
                                autoPlayControl: false,
                                borderRadius: 0,
                                direction: "left",
                                dragControl: true,
                                effectsOptions: {
                                    effectsHover: true,
                                    effectsOpacity: 1,
                                    effectsPerspective: 1200,
                                    effectsRotate: 0,
                                    effectsScale: 1,
                                    playOffscreen: false
                                },
                                fadeOptions: {
                                    fadeAlpha: 0,
                                    fadeContent: false,
                                    fadeInset: 0,
                                    fadeWidth: 25,
                                    overflow: false
                                },
                                gap: 20,
                                height: "100%",
                                id: "P9kZnKNgR",
                                intervalControl: 3,
                                itemAmount: 1,
                                layoutId: "P9kZnKNgR",
                                padding: 0,
                                paddingBottom: 50,
                                paddingLeft: 0,
                                paddingPerSide: true,
                                paddingRight: 0,
                                paddingTop: 0,
                                progressOptions: {
                                    dotsActiveOpacity: 1,
                                    dotsBackground: "rgba(0, 0, 0, 0)",
                                    dotsBlur: 0,
                                    dotsFill: "var(--token-293955a5-6f9a-470e-8eb8-8f52a27509f0, rgb(16, 16, 20))",
                                    dotsGap: 10,
                                    dotsInset: 10,
                                    dotSize: 10,
                                    dotsOpacity: .5,
                                    dotsPadding: 10,
                                    dotsRadius: 50,
                                    showProgressDots: true
                                },
                                slots: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1gl0j1n-container",
                                        "data-framer-name": "Review 1",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "PfVGrK8Eu-container",
                                        name: "Review 1",
                                        nodeId: "PfVGrK8Eu",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "PfVGrK8Eu",
                                            layoutId: "PfVGrK8Eu",
                                            name: "Review 1",
                                            NQ6B20sX9: "Darma Gunawan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Fasiltas lengkap dan super bersih. Kasur spring bednya empuk banget, tidur jadi makin nyenyak dan bangun fresh tiap pagi.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1280,
                                                pixelWidth: 960,
                                                src: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp",
                                                srcSet: "https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp?scale-down-to=1024 768w,https://framerusercontent.com/images/Amjhb0Wjn3MoaWtre7mwv40Q7IU.webp 960w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1nvjbrn-container",
                                        "data-framer-name": "Review 2",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "a46o4u2Vr-container",
                                        name: "Review 2",
                                        nodeId: "a46o4u2Vr",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "a46o4u2Vr",
                                            layoutId: "a46o4u2Vr",
                                            name: "Review 2",
                                            NQ6B20sX9: "Rayhan",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Lokasinya tuh mantap banget, gampang banget akses ke mana-mana. Deket mall, transportasi, sama tempat nongkrong hits. Pokoknya praktis!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp",
                                                srcSet: "https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/V3HoY6rj1VtLFJ5OI3QTphLaZWk.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-igbayv-container",
                                        "data-framer-name": "Review 3",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "pkAzOLoRU-container",
                                        name: "Review 3",
                                        nodeId: "pkAzOLoRU",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "pkAzOLoRU",
                                            layoutId: "pkAzOLoRU",
                                            name: "Review 3",
                                            NQ6B20sX9: "Adam",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Promo buat penghuni baru bikin kantong nggak bolong! Diskonnya asik, plus laundry gratis bikin hidup jadi makin mudah.",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 640,
                                                pixelWidth: 640,
                                                src: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp",
                                                srcSet: "https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp?scale-down-to=512 512w,https://framerusercontent.com/images/zFmudbXSfa5rfYsrukq26s4gl7g.webp 640w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1rjk45j-container",
                                        "data-framer-name": "Review 4",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "H5brTFDHx-container",
                                        name: "Review 4",
                                        nodeId: "H5brTFDHx",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "H5brTFDHx",
                                            layoutId: "H5brTFDHx",
                                            name: "Review 4",
                                            NQ6B20sX9: "Salsa",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Kebersihan dan keamanan selalu top! Kosrutdua serius banget jaga kenyamanan penghuninya, jadi aku selalu tenang tinggal di sini.",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 1200,
                                                pixelWidth: 675,
                                                src: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp",
                                                srcSet: "https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp?scale-down-to=1024 576w,https://framerusercontent.com/images/840Nbz40PjB0dO0FdDGBUG8Zog.webp 675w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1ckxv38-container",
                                        "data-framer-name": "Review 5",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "V8rZpDF2c-container",
                                        name: "Review 5",
                                        nodeId: "V8rZpDF2c",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "V8rZpDF2c",
                                            layoutId: "V8rZpDF2c",
                                            name: "Review 5",
                                            NQ6B20sX9: "Ibnu",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "Suasananya cozy dan tenang, cocok banget buat yang suka fokus belajar atau kerja. Fasilitas masaknya lengkap, tinggal masak deh kapan aja!",
                                            variant: "r8ZzAWHL8",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 603,
                                                pixelWidth: 632,
                                                src: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp",
                                                srcSet: "https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp?scale-down-to=512 512w,https://framerusercontent.com/images/96LoBGs3st3fPoKOUHCZ2EDoiw.webp 632w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 285,
                                    width: "400px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-11gkorv-container",
                                        "data-framer-name": "Review 6",
                                        inComponentSlot: true,
                                        isModuleExternal: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "mHbGMiop_-container",
                                        name: "Review 6",
                                        nodeId: "mHbGMiop_",
                                        rendersWithMotion: true,
                                        scopeId: "u37Ksg0Ot",
                                        children: /*#__PURE__*/ _jsx(ReviewCard, {
                                            height: "100%",
                                            id: "mHbGMiop_",
                                            layoutId: "mHbGMiop_",
                                            name: "Review 6",
                                            NQ6B20sX9: "Noel",
                                            style: {
                                                height: "100%",
                                                width: "100%"
                                            },
                                            t9TK5wU0p: "WiFi super kenceng dan stabil abis, nggak ada drama buffering pas kerja online atau streaming. Bikin semangat kerja di kos!",
                                            variant: "ICMB543r_",
                                            VuQLO25Gf: addImageAlt({
                                                pixelHeight: 610,
                                                pixelWidth: 580,
                                                src: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp",
                                                srcSet: "https://framerusercontent.com/images/HGfbBlD9v0S2YWcKKM42OSZOOo.webp 580w"
                                            }, ""),
                                            width: "100%"
                                        })
                                    })
                                })],
                                startFrom: 0,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                transitionControl: {
                                    damping: 40,
                                    delay: 0,
                                    mass: 1,
                                    stiffness: 200,
                                    type: "spring"
                                },
                                width: "100%"
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Gb85t.framer-1bub42z, .framer-Gb85t .framer-1bub42z { display: block; }", ".framer-Gb85t.framer-prv7f3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1440px; }", ".framer-Gb85t .framer-1r47pz1-container, .framer-Gb85t .framer-9ex90p-container { flex: none; height: 300px; position: relative; width: 100%; }", ".framer-Gb85t .framer-1gl0j1n-container, .framer-Gb85t .framer-1nvjbrn-container, .framer-Gb85t .framer-igbayv-container, .framer-Gb85t .framer-1rjk45j-container, .framer-Gb85t .framer-1ckxv38-container, .framer-Gb85t .framer-11gkorv-container { height: 285px; position: relative; width: 400px; }", ".framer-Gb85t .framer-1nhil04-container { flex: none; height: 399px; position: relative; width: 100%; }", ".framer-Gb85t.framer-v-gh6fsa.framer-prv7f3 { padding: 0px 20px 0px 20px; width: 390px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 632
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"D70eLlKIA":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Frameru37Ksg0Ot = withCSS(Component, css, "framer-Gb85t");
export default Frameru37Ksg0Ot;
Frameru37Ksg0Ot.displayName = "Testimonials";
Frameru37Ksg0Ot.defaultProps = {
    height: 632,
    width: 1440
};
addPropertyControls(Frameru37Ksg0Ot, {
    variant: {
        options: ["weqKRlLlh", "D70eLlKIA"],
        optionTitles: ["Desktop", "Mobile"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(Frameru37Ksg0Ot, [{
    explicitInter: true,
    fonts: []
}, ...ReviewCardFonts, ...TickerFonts, ...SlideshowFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Frameru37Ksg0Ot",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"D70eLlKIA\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "1440",
                "framerIntrinsicHeight": "632"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./u37Ksg0Ot.map