// Generated by Framer (f7ce5cf)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/WTC1ahzOwMo2CaFLVlVD/KGhQx5zHJt51cHcHGlw0/qL0mZkKEG.js";
const serializationHash = "framer-YFgD8";
const variantClassNames = {
    a00czxF5o: "framer-v-1w09vx6"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        p8Invp0nd: title ? ? props.p8Invp0nd ? ? "What We Offer"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        p8Invp0nd,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "a00czxF5o",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1w09vx6", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "a00czxF5o",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "1px",
                        "--border-color": "var(--token-d9d8d5ef-768f-4d6d-a4c1-1b6a1792413c, rgb(199, 199, 199))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor: "var(--token-b94fc636-02ac-4053-8f72-b23ff50405a3, rgb(243, 243, 243))",
                        borderBottomLeftRadius: 32,
                        borderBottomRightRadius: 32,
                        borderTopLeftRadius: 32,
                        borderTopRightRadius: 32,
                        ...style
                    },
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1f8staf",
                                "data-styles-preset": "qL0mZkKEG",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-fa16a3ef-909b-4fe8-b9b6-d5a056139983, rgb(44, 44, 44)))"
                                },
                                children: "What We Offer"
                            })
                        }),
                        className: "framer-1y692v0",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "pNh81Ajne",
                        style: {
                            "--extracted-r6o4lv": "var(--token-fa16a3ef-909b-4fe8-b9b6-d5a056139983, rgb(44, 44, 44))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: p8Invp0nd,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-YFgD8.framer-1wi2wbt, .framer-YFgD8 .framer-1wi2wbt { display: block; }", ".framer-YFgD8.framer-1w09vx6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 24px 4px 24px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-YFgD8 .framer-1y692v0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-YFgD8.framer-1w09vx6 { gap: 0px; } .framer-YFgD8.framer-1w09vx6 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-YFgD8.framer-1w09vx6 > :first-child { margin-left: 0px; } .framer-YFgD8.framer-1w09vx6 > :last-child { margin-right: 0px; } }", ...sharedStyle.css, '.framer-YFgD8[data-border="true"]::after, .framer-YFgD8 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 31
 * @framerIntrinsicWidth 166
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"p8Invp0nd":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerhTJRZmVtO = withCSS(Component, css, "framer-YFgD8");
export default FramerhTJRZmVtO;
FramerhTJRZmVtO.displayName = "Badge";
FramerhTJRZmVtO.defaultProps = {
    height: 31,
    width: 166
};
addPropertyControls(FramerhTJRZmVtO, {
    p8Invp0nd: {
        defaultValue: "What We Offer",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerhTJRZmVtO, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerhTJRZmVtO",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicHeight": "31",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "166",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"p8Invp0nd\":\"title\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./hTJRZmVtO.map