// Generated by Framer (f7ce5cf)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-iPo1t";
const variantClassNames = {
    WWz7QOFHL: "framer-v-w3p6pk"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    image1,
    width,
    ...props
}) => {
    return { ...props,
        EFUeAuPYS: image1 ? ? props.EFUeAuPYS ? ? {
            alt: "",
            pixelHeight: 600,
            pixelWidth: 600,
            src: "https://framerusercontent.com/images/LT4HqyTKPVut6GctXkg8TVWkw8.jpg?scale-down-to=512",
            srcSet: "https://framerusercontent.com/images/LT4HqyTKPVut6GctXkg8TVWkw8.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/LT4HqyTKPVut6GctXkg8TVWkw8.jpg 600w"
        }
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        EFUeAuPYS,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "WWz7QOFHL",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(componentViewport ? .y || 0),
                        pixelHeight: 600,
                        pixelWidth: 600,
                        sizes: componentViewport ? .width || "100vw",
                        ...toResponsiveImage(EFUeAuPYS)
                    },
                    className: cx(scopingClassNames, "framer-w3p6pk", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "WWz7QOFHL",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "3px",
                        "--border-color": "var(--token-528a4e50-1a33-4ebe-a3b3-4f0f1508d312, rgb(255, 255, 255))",
                        "--border-left-width": "3px",
                        "--border-right-width": "3px",
                        "--border-style": "solid",
                        "--border-top-width": "3px",
                        borderBottomLeftRadius: 999,
                        borderBottomRightRadius: 999,
                        borderTopLeftRadius: 999,
                        borderTopRightRadius: 999,
                        ...style
                    }
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-iPo1t.framer-19lael4, .framer-iPo1t .framer-19lael4 { display: block; }", ".framer-iPo1t.framer-w3p6pk { height: 70px; overflow: visible; position: relative; width: 70px; }", '.framer-iPo1t[data-border="true"]::after, .framer-iPo1t [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 70
 * @framerIntrinsicWidth 70
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"EFUeAuPYS":"image1"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramermHZkaKnhe = withCSS(Component, css, "framer-iPo1t");
export default FramermHZkaKnhe;
FramermHZkaKnhe.displayName = "Agent Avatar";
FramermHZkaKnhe.defaultProps = {
    height: 70,
    width: 70
};
addPropertyControls(FramermHZkaKnhe, {
    EFUeAuPYS: {
        __defaultAssetReference: "data:framer/asset-reference,LT4HqyTKPVut6GctXkg8TVWkw8.jpg?originalFilename=agent-1.jpg&preferredSize=auto",
        __vekterDefault: {
            alt: "",
            assetReference: "data:framer/asset-reference,LT4HqyTKPVut6GctXkg8TVWkw8.jpg?originalFilename=agent-1.jpg&preferredSize=auto"
        },
        title: "Image 1",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramermHZkaKnhe, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramermHZkaKnhe",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "70",
                "framerIntrinsicHeight": "70",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"EFUeAuPYS\":\"image1\"}",
                "framerDisplayContentsDiv": "false"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./mHZkaKnhe.map