// Generated by Framer (9aabefb)
import siteMetadata from "https://framerusercontent.com/modules/4hQAw5roefvd1Oi0OKXK/YxMhlCs2xDLWBftEiyfy/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "72rtr7",
            mediaQuery: "(min-width: 1280px)"
        }, {
            hash: "qw1gvc",
            mediaQuery: "(min-width: 810px) and (max-width: 1279.98px)"
        }, {
            hash: "osgdk9",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            bN06hGKHy: "faq",
            C60RUggHu: "testimonials",
            E5xbXrjqj: "hero-1",
            H0mCFJhs_: "property",
            HyRYoqbuA: "contact",
            IWGBTIPsE: "about-1",
            KfjxAt9m1: "property-1",
            l801ubO5I: "hero",
            ngXQB110e: "about",
            wam4hSPE1: "property-2",
            wfjwGxYhP: "about-2",
            Wnz3Ar2w2: "feature-service"
        },
        robots: "max-image-preview:large",
        serializationId: "framer-nIs4F",
        title: siteMetadata(params, activeLocale).title || "Home",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}