// Generated by Framer (53c1d35)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as t,
    QueryEngine as a
} from "framer";
import {
    DatabaseCollection as r,
    DatabaseDictionaryIndex as o
} from "./XIFZ8EqFs-0.js";
import {
    resolveRichText as m
} from "./XIFZ8EqFs-1.js";
let i = {
        ApZRzs0la: {
            isNullable: !0,
            type: l.Boolean
        },
        BIHKdHFNQ: {
            isNullable: !0,
            type: l.String
        },
        bj5jjARGE: {
            isNullable: !0,
            type: l.String
        },
        bmVVf1i8J: {
            isNullable: !0,
            type: l.Number
        },
        BsqU_EWYx: {
            isNullable: !0,
            type: l.Boolean
        },
        CKoLR4lvB: {
            isNullable: !0,
            type: l.Boolean
        },
        cMQmTRtYW: {
            isNullable: !0,
            type: l.String
        },
        csMVEMOXg: {
            isNullable: !0,
            type: l.Number
        },
        glRRqGQQx: {
            isNullable: !0,
            type: l.Boolean
        },
        gNq59lHvB: {
            isNullable: !0,
            type: l.String
        },
        HA_dwndZa: {
            isNullable: !0,
            type: l.String
        },
        hjUbw3O06: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        iT4mk5Y8V: {
            isNullable: !0,
            type: l.String
        },
        Jmr1jravF: {
            isNullable: !0,
            type: l.String
        },
        JQcjMp1ZN: {
            isNullable: !0,
            type: l.Boolean
        },
        khE4Pw9kd: {
            isNullable: !0,
            type: l.Boolean
        },
        Kwzjh306m: {
            isNullable: !0,
            type: l.String
        },
        kxeO8DlEp: {
            isNullable: !0,
            type: l.Number
        },
        KXTeIiqGH: {
            isNullable: !0,
            type: l.String
        },
        LiYycyVgm: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        MFC47SGrK: {
            isNullable: !0,
            type: l.String
        },
        MQiAS6Rex: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        oaGLFDbGt: {
            isNullable: !0,
            type: l.String
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        qnQnfOHwe: {
            isNullable: !0,
            type: l.String
        },
        rk0o_0BZN: {
            isNullable: !0,
            type: l.String
        },
        sTJTVnExL: {
            isNullable: !0,
            type: l.String
        },
        suWAxnO7G: {
            isNullable: !0,
            type: l.Boolean
        },
        ty_M8qr9Q: {
            isNullable: !0,
            type: l.Number
        },
        UVqBG6QEK: {
            isNullable: !0,
            type: l.Boolean
        },
        VgT7j2cba: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        WswOdF1cH: {
            isNullable: !0,
            type: l.Boolean
        },
        xFwIq11kh: {
            isNullable: !0,
            type: l.Link
        },
        XITNSCjVj: {
            isNullable: !0,
            type: l.String
        },
        YSlW0vm08: {
            isNullable: !0,
            type: l.Enum
        }
    },
    n = ["id"],
    s = {
        type: 1
    },
    c = ["previousItemId"],
    u = ["nextItemId"],
    f = ["id", "MQiAS6Rex"],
    d = ["MQiAS6Rex", "id"],
    p = ["HA_dwndZa"],
    y = {
        type: 0
    },
    g = ["MQiAS6Rex"],
    w = ["LiYycyVgm"],
    F = ["hjUbw3O06"],
    N = ["VgT7j2cba"],
    h = ["Jmr1jravF"],
    S = ["cMQmTRtYW"],
    I = ["oaGLFDbGt"],
    R = ["sTJTVnExL"],
    x = ["KXTeIiqGH"],
    q = ["YSlW0vm08"],
    E = ["BIHKdHFNQ"],
    L = ["rk0o_0BZN"],
    b = ["qnQnfOHwe"],
    V = ["iT4mk5Y8V"],
    Z = ["XITNSCjVj"],
    X = ["Kwzjh306m"],
    B = ["bj5jjARGE"],
    U = ["gNq59lHvB"],
    j = ["WswOdF1cH"],
    G = ["JQcjMp1ZN"],
    v = ["glRRqGQQx"],
    Q = ["CKoLR4lvB"],
    M = ["khE4Pw9kd"],
    A = ["suWAxnO7G"],
    K = ["UVqBG6QEK"],
    P = ["BsqU_EWYx"],
    T = ["ApZRzs0la"],
    k = ["bmVVf1i8J"],
    H = ["ty_M8qr9Q"],
    O = ["csMVEMOXg"],
    W = ["kxeO8DlEp"],
    Y = ["xFwIq11kh"],
    C = ["MFC47SGrK"],
    J = [],
    _ = e => {
        let l = J[e];
        if (l) return l().then(e => e.default);
    },
    D = new a,
    z = new t(D),
    $ = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./XIFZ8EqFs-chunk-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")],
                indexes: [new o({
                    collation: s,
                    collectionSchema: i,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 289
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: i,
                    fieldNames: c,
                    range: {
                        from: 289,
                        to: 577
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: i,
                    fieldNames: u,
                    range: {
                        from: 577,
                        to: 861
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: i,
                    fieldNames: f,
                    range: {
                        from: 861,
                        to: 1330
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: i,
                    fieldNames: d,
                    range: {
                        from: 1330,
                        to: 1799
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: p,
                    range: {
                        from: 1799,
                        to: 2108
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: g,
                    range: {
                        from: 2108,
                        to: 2417
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: w,
                    range: {
                        from: 2417,
                        to: 7771
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: F,
                    range: {
                        from: 7771,
                        to: 13114
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: N,
                    range: {
                        from: 13114,
                        to: 18547
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: h,
                    range: {
                        from: 18547,
                        to: 19778
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: S,
                    range: {
                        from: 19778,
                        to: 20068
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: I,
                    range: {
                        from: 20068,
                        to: 20320
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: R,
                    range: {
                        from: 20320,
                        to: 20527
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: x,
                    range: {
                        from: 20527,
                        to: 20734
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: q,
                    range: {
                        from: 20734,
                        to: 21030
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: E,
                    range: {
                        from: 21030,
                        to: 23814
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: L,
                    range: {
                        from: 23814,
                        to: 25045
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: b,
                    range: {
                        from: 25045,
                        to: 25737
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: V,
                    range: {
                        from: 25737,
                        to: 26198
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: Z,
                    range: {
                        from: 26198,
                        to: 26593
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: X,
                    range: {
                        from: 26593,
                        to: 27032
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: B,
                    range: {
                        from: 27032,
                        to: 27614
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: U,
                    range: {
                        from: 27614,
                        to: 28317
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: j,
                    range: {
                        from: 28317,
                        to: 28481
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: G,
                    range: {
                        from: 28481,
                        to: 28645
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: v,
                    range: {
                        from: 28645,
                        to: 28809
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: Q,
                    range: {
                        from: 28809,
                        to: 28973
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: M,
                    range: {
                        from: 28973,
                        to: 29137
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: A,
                    range: {
                        from: 29137,
                        to: 29301
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: K,
                    range: {
                        from: 29301,
                        to: 29465
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: P,
                    range: {
                        from: 29465,
                        to: 29629
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: T,
                    range: {
                        from: 29629,
                        to: 29793
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: k,
                    range: {
                        from: 29793,
                        to: 30034
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: H,
                    range: {
                        from: 30034,
                        to: 30275
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: O,
                    range: {
                        from: 30275,
                        to: 30516
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: W,
                    range: {
                        from: 30516,
                        to: 30757
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: Y,
                    range: {
                        from: 30757,
                        to: 36104
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                }), new o({
                    collation: y,
                    collectionSchema: i,
                    fieldNames: C,
                    range: {
                        from: 36104,
                        to: 36341
                    },
                    url: new URL("./XIFZ8EqFs-indexes-default-0.framercms", "https://framerusercontent.com/modules/toB6GILb3yIwxDvPD5Rd/x2HQFkXRVy7sDkwJsdiu/XIFZ8EqFs.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: m,
                resolveVectorSetItem: _,
                schema: i
            })
        },
        displayName: "Wonodri Baru"
    };
export default $;
e($, {
    HA_dwndZa: {
        defaultValue: "",
        title: "unknow",
        type: l.String
    },
    MQiAS6Rex: {
        title: "Slug",
        type: l.String
    },
    LiYycyVgm: {
        title: "Property Cover Image",
        type: l.ResponsiveImage
    },
    hjUbw3O06: {
        title: "Property Small Image 1",
        type: l.ResponsiveImage
    },
    VgT7j2cba: {
        title: "Property Small Image 2",
        type: l.ResponsiveImage
    },
    Jmr1jravF: {
        defaultValue: "",
        title: "Property Location",
        type: l.String
    },
    cMQmTRtYW: {
        defaultValue: "",
        title: "Property Price",
        type: l.String
    },
    oaGLFDbGt: {
        defaultValue: "",
        title: "Property Area",
        type: l.String
    },
    sTJTVnExL: {
        defaultValue: "",
        title: "Property Rooms",
        type: l.String
    },
    KXTeIiqGH: {
        defaultValue: "",
        title: "Property Bathrooms",
        type: l.String
    },
    YSlW0vm08: {
        defaultValue: "cKFLGGGJc",
        options: ["cKFLGGGJc", "abE2IuPAl"],
        optionTitles: ["Penuh", "Kosong"],
        title: "Property Category",
        type: l.Enum
    },
    BIHKdHFNQ: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Overview",
        type: l.String
    },
    rk0o_0BZN: {
        defaultValue: "52.37588, 4.891295",
        title: "Google Map",
        type: l.String
    },
    qnQnfOHwe: {
        defaultValue: "",
        title: "Bullet Point 1",
        type: l.String
    },
    iT4mk5Y8V: {
        defaultValue: "",
        title: "Bullet Point 2",
        type: l.String
    },
    XITNSCjVj: {
        defaultValue: "",
        title: "Bullet Point 3",
        type: l.String
    },
    Kwzjh306m: {
        defaultValue: "",
        title: "Bullet Point 4",
        type: l.String
    },
    bj5jjARGE: {
        defaultValue: "",
        title: "Bullet Point 5",
        type: l.String
    },
    gNq59lHvB: {
        defaultValue: "",
        title: "Bullet Point 6",
        type: l.String
    },
    WswOdF1cH: {
        defaultValue: !0,
        title: "Peralatan Tidur",
        type: l.Boolean
    },
    JQcjMp1ZN: {
        defaultValue: !0,
        title: "Lemari Pakaian",
        type: l.Boolean
    },
    glRRqGQQx: {
        defaultValue: !0,
        title: "Meja Kerja",
        type: l.Boolean
    },
    CKoLR4lvB: {
        defaultValue: !0,
        title: "Internet",
        type: l.Boolean
    },
    khE4Pw9kd: {
        defaultValue: !0,
        title: "AC",
        type: l.Boolean
    },
    suWAxnO7G: {
        defaultValue: !0,
        title: "Kipas Angin",
        type: l.Boolean
    },
    UVqBG6QEK: {
        defaultValue: !0,
        title: "Peralatan Mandi",
        type: l.Boolean
    },
    BsqU_EWYx: {
        defaultValue: !0,
        title: "Gantungan Baju",
        type: l.Boolean
    },
    ApZRzs0la: {
        defaultValue: !1,
        title: "Kamar Mandi Dalam",
        type: l.Boolean
    },
    bmVVf1i8J: {
        defaultValue: 1,
        title: "qty",
        type: l.Number
    },
    ty_M8qr9Q: {
        defaultValue: 2,
        title: "qty 2",
        type: l.Number
    },
    csMVEMOXg: {
        defaultValue: 3,
        title: "qty 3",
        type: l.Number
    },
    kxeO8DlEp: {
        defaultValue: 4,
        title: "qty 4",
        type: l.Number
    },
    xFwIq11kh: {
        title: "Pesan Kamar",
        type: l.Link
    },
    MFC47SGrK: {
        defaultValue: "",
        title: "Jenis Kamar",
        type: l.String
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/XIFZ8EqFs:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/XIFZ8EqFs:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const YSlW0vm08ToDisplayName = (e, l) => {
    switch (l ? .fallback, e) {
        case "cKFLGGGJc":
            return "Penuh";
        case "abE2IuPAl":
            return "Kosong";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    YSlW0vm08: YSlW0vm08ToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await z.get({
            from: {
                data: $,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "MQiAS6Rex",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .MQiAS6Rex;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await z.get({
            from: {
                data: $,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "MQiAS6Rex",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "YSlW0vm08ToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerCollectionUtils": "1",
                "framerSlug": "MQiAS6Rex",
                "framerCollectionId": "XIFZ8EqFs",
                "framerData": "",
                "framerColorSyntax": "false",
                "framerRecordIdKey": "id",
                "framerEnumToDisplayNameUtils": "2"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}