// Generated by Framer (14b65b1)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import FAQComponent from "https://framerusercontent.com/modules/4RJvTKWeZfn1uSPG06KT/Ij02HKqymz6ASnyi1C9c/bLLk7F8Ji.js";
const FAQComponentFonts = getFonts(FAQComponent);
const cycleOrder = ["xgdIZ9S0A", "P25CYiMjS"];
const serializationHash = "framer-hu2gD";
const variantClassNames = {
    P25CYiMjS: "framer-v-1run69l",
    xgdIZ9S0A: "framer-v-femath"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "xgdIZ9S0A",
    Phone: "P25CYiMjS"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "xgdIZ9S0A"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "xgdIZ9S0A",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-femath", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "xgdIZ9S0A",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        P25CYiMjS: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 0 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 0 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1f1co51-container",
                            layoutDependency: layoutDependency,
                            layoutId: "RSS6qE4h_-container",
                            nodeId: "RSS6qE4h_",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Apa aja pilihan kamar yang tersedia di Kosrutdua?",
                                height: "100%",
                                id: "RSS6qE4h_",
                                layoutId: "RSS6qE4h_",
                                LMw0Eai2r: "Kamu bisa pilih antara kamar ber-AC atau non-AC, total ada 27 kamar yang bisa kamu pilih sesuai kebutuhan.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 131 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 131 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1ugfngx-container",
                            layoutDependency: layoutDependency,
                            layoutId: "vNYGFteDJ-container",
                            nodeId: "vNYGFteDJ",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Gimana cara dapetin diskon buat penghuni baru?",
                                height: "100%",
                                id: "vNYGFteDJ",
                                layoutId: "vNYGFteDJ",
                                LMw0Eai2r: "Cukup jadi penghuni kos.rutdua maka kamu akan dapat diskon sebesar Rp.100.000 sebanyak 3 kali dalam 3 bulan pertama.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 262 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 262 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1j6pdmi-container",
                            layoutDependency: layoutDependency,
                            layoutId: "x5hAXlo5t-container",
                            nodeId: "x5hAXlo5t",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Apakah ada fasilitas laundry di Kosrutdua?",
                                height: "100%",
                                id: "x5hAXlo5t",
                                layoutId: "x5hAXlo5t",
                                LMw0Eai2r: "Ada dong! Kamu bisa pakai layanan laundry gratis sampai 15 kg per bulan, jadi nggak pusing urusan cuci baju.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 393 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 393 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-jrn79d-container",
                            layoutDependency: layoutDependency,
                            layoutId: "fVTLd01qy-container",
                            nodeId: "fVTLd01qy",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Boleh masak ga di kos?",
                                height: "100%",
                                id: "fVTLd01qy",
                                layoutId: "fVTLd01qy",
                                LMw0Eai2r: "Boleh banget! Kami sediakan kompor, tabung gas, meja, dan freezer supaya kamu bisa masak seenak kamu.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 524 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 524 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-axi988-container",
                            layoutDependency: layoutDependency,
                            layoutId: "XBN3arKb1-container",
                            nodeId: "XBN3arKb1",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Apakah kamar sudah lengkap dengan perabotan?",
                                height: "100%",
                                id: "XBN3arKb1",
                                layoutId: "XBN3arKb1",
                                LMw0Eai2r: "Iya, setiap kamar lengkap dengan spring bed, bantal, lemari, meja kerja, kipas angin atau AC, dan perlengkapan mandi.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 655 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 655 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1rxpoyw-container",
                            layoutDependency: layoutDependency,
                            layoutId: "ceURAZwEE-container",
                            nodeId: "ceURAZwEE",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Apakah ada wifi di kos?",
                                height: "100%",
                                id: "ceURAZwEE",
                                layoutId: "ceURAZwEE",
                                LMw0Eai2r: "Pasti! WiFi cepat dan gratis siap menemani aktivitas kamu setiap hari.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 786 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 786 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-lwwx69-container",
                            layoutDependency: layoutDependency,
                            layoutId: "pAxu0OJ8R-container",
                            nodeId: "pAxu0OJ8R",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Kapan jadwal pengambilan laundry?",
                                height: "100%",
                                id: "pAxu0OJ8R",
                                layoutId: "pAxu0OJ8R",
                                LMw0Eai2r: "Laundry diambil setiap Senin dan Kamis pagi jam 06.00 WIB, jadi siap-siap taruh tas laundry di depan kamar ya!",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 131,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 801) - 0 - 1048) / 2 + 917 + 0),
                        ...addPropertyOverrides({
                            P25CYiMjS: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 878) - 0 - 1048) / 2 + 917 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1tiiicb-container",
                            layoutDependency: layoutDependency,
                            layoutId: "bKKQlzmaa-container",
                            nodeId: "bKKQlzmaa",
                            rendersWithMotion: true,
                            scopeId: "q4hWjzMvS",
                            children: /*#__PURE__*/ _jsx(FAQComponent, {
                                dNN6Xuq1x: "Apa yang harus saya siapkan buat jadi penghuni Kosrutdua?",
                                height: "100%",
                                id: "bKKQlzmaa",
                                layoutId: "bKKQlzmaa",
                                LMw0Eai2r: "Kamu perlu siapin foto KTP, nomor telepon kamu, dan nomor telepon kerabat terdekat sebagai persyaratan pendaftaran.",
                                style: {
                                    width: "100%"
                                },
                                variant: "kx0qMT_Lh",
                                width: "100%",
                                ...addPropertyOverrides({
                                    P25CYiMjS: {
                                        variant: "YhY9IHJ_c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-hu2gD.framer-slrws, .framer-hu2gD .framer-slrws { display: block; }", ".framer-hu2gD.framer-femath { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 784px; }", ".framer-hu2gD .framer-1f1co51-container, .framer-hu2gD .framer-1ugfngx-container, .framer-hu2gD .framer-1j6pdmi-container, .framer-hu2gD .framer-jrn79d-container, .framer-hu2gD .framer-axi988-container, .framer-hu2gD .framer-1rxpoyw-container, .framer-hu2gD .framer-lwwx69-container, .framer-hu2gD .framer-1tiiicb-container { flex: none; height: auto; position: relative; width: 100%; }", ".framer-hu2gD.framer-v-1run69l.framer-femath { width: 380px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 801
 * @framerIntrinsicWidth 784
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"P25CYiMjS":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerq4hWjzMvS = withCSS(Component, css, "framer-hu2gD");
export default Framerq4hWjzMvS;
Framerq4hWjzMvS.displayName = "FAQ Wrap";
Framerq4hWjzMvS.defaultProps = {
    height: 801,
    width: 784
};
addPropertyControls(Framerq4hWjzMvS, {
    variant: {
        options: ["xgdIZ9S0A", "P25CYiMjS"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(Framerq4hWjzMvS, [{
    explicitInter: true,
    fonts: []
}, ...FAQComponentFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "Framerq4hWjzMvS",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "784",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"P25CYiMjS\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "801"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./q4hWjzMvS.map