// Generated by Framer (f7ce5cf)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/WTC1ahzOwMo2CaFLVlVD/KGhQx5zHJt51cHcHGlw0/qL0mZkKEG.js";
const enabledGestures = {
    mNOTU3eD5: {
        hover: true,
        pressed: true
    }
};
const serializationHash = "framer-hACUu";
const variantClassNames = {
    mNOTU3eD5: "framer-v-130iky8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .2,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        NSlgrnoUy: link ? ? props.NSlgrnoUy,
        P3nSeb5Pv: title ? ? props.P3nSeb5Pv ? ? "Submit"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        P3nSeb5Pv,
        NSlgrnoUy,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "mNOTU3eD5",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: NSlgrnoUy,
                    motionChild: true,
                    nodeId: "mNOTU3eD5",
                    openInNewTab: false,
                    scopeId: "oMOCfSp2Q",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-130iky8",className,classNames)} framer-1ecydf7`,
                        "data-framer-name": "Default",
                        "data-reset": "button",
                        layoutDependency: layoutDependency,
                        layoutId: "mNOTU3eD5",
                        ref: refBinding,
                        style: {
                            backgroundColor: "var(--token-e1eaf7ec-6a2b-469c-8ec1-579f75fde613, rgb(0, 0, 0))",
                            borderBottomLeftRadius: 99,
                            borderBottomRightRadius: 99,
                            borderTopLeftRadius: 99,
                            borderTopRightRadius: 99,
                            ...style
                        },
                        variants: {
                            "mNOTU3eD5-hover": {
                                backgroundColor: "var(--token-fa16a3ef-909b-4fe8-b9b6-d5a056139983, rgb(44, 44, 44))"
                            },
                            "mNOTU3eD5-pressed": {
                                backgroundColor: "var(--token-fa16a3ef-909b-4fe8-b9b6-d5a056139983, rgb(44, 44, 44))"
                            }
                        },
                        ...addPropertyOverrides({
                            "mNOTU3eD5-hover": {
                                "data-framer-name": undefined
                            },
                            "mNOTU3eD5-pressed": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1f8staf",
                                    "data-styles-preset": "qL0mZkKEG",
                                    children: "Submit"
                                })
                            }),
                            className: "framer-1au07xj",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "ES5BTK8OJ",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: P3nSeb5Pv,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-hACUu.framer-1ecydf7, .framer-hACUu .framer-1ecydf7 { display: block; }", ".framer-hACUu.framer-130iky8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 12px 0px 12px 0px; position: relative; text-decoration: none; width: 240px; }", ".framer-hACUu .framer-1au07xj { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-hACUu.framer-130iky8 { gap: 0px; } .framer-hACUu.framer-130iky8 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-hACUu.framer-130iky8 > :first-child { margin-left: 0px; } .framer-hACUu.framer-130iky8 > :last-child { margin-right: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 47
 * @framerIntrinsicWidth 240
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VR6oZ2CrB":{"layout":["fixed","auto"]},"awLfnhnOH":{"layout":["fixed","auto"]}}}
 * @framerVariables {"P3nSeb5Pv":"title","NSlgrnoUy":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameroMOCfSp2Q = withCSS(Component, css, "framer-hACUu");
export default FrameroMOCfSp2Q;
FrameroMOCfSp2Q.displayName = "Sidebar Button";
FrameroMOCfSp2Q.defaultProps = {
    height: 47,
    width: 240
};
addPropertyControls(FrameroMOCfSp2Q, {
    P3nSeb5Pv: {
        defaultValue: "Submit",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    NSlgrnoUy: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FrameroMOCfSp2Q, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameroMOCfSp2Q",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "240",
                "framerVariables": "{\"P3nSeb5Pv\":\"title\",\"NSlgrnoUy\":\"link\"}",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "47",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"VR6oZ2CrB\":{\"layout\":[\"fixed\",\"auto\"]},\"awLfnhnOH\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./oMOCfSp2Q.map